# Generated by Django 4.1.7 on 2023-02-21 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emertimi', models.CharField(max_length=250, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fakulteti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperketfakultetit', to='smak.fakulteti')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Programi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emertimi', models.CharField(max_length=500, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('departmaneti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iperketdepartamentit', to='smak.departamenti')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.AddIndex(
            model_name='programi',
            index=models.Index(fields=['-emertimi'], name='smak_progra_emertim_aff751_idx'),
        ),
    ]
