# Generated by Django 4.1.7 on 2023-02-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smak', '0002_departamenti_programi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programi',
            old_name='departmaneti',
            new_name='departamenti',
        ),
    ]
